name: CratePlugin
description: wdym?
author: yeboiCravez
version: 1.0
main: cratesPackage.CratesMain
depend: [PowerUpsPL, LevelsPlugin]
commands:
 crates:
   description: shows your crate key balance
 cspawn:
   description: spawns in a crate
 cgive:
   description: gives a crate to someone  